### ISSUE TITLE
TokenStream expanded to xxx finite strings

### ISSUE THREAD

**Issue by missinglink** [pelias/elasticsearch-plugin#5]
I am getting this error when importing geonames using the plugin, it's also been reported by @sevko 

```IllegalArgumentException[TokenStream expanded to 360 finite strings. Only <= 256 finite strings are supported```

Searching google and you'll find the top result is actually from the old ruby version of Pelias, which seemed to suffer the same issue: https://github.com/pelias/pelias/issues/13

ref: https://github.com/elasticsearch/elasticsearch/blob/master/src/main/java/org/elasticsearch/search/suggest/completion/CompletionTokenStream.java#L66

Just a guess, are some of the synonyms too long?

ref: `max_token_length` http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/analysis-standard-analyzer.html

cc/ @hkrishna 

Connected to pelias/pelias#33

**Comment by torinaki** [comment]
I experience this issue when split_on_case_change is enabled for word_delimiter filter and I'm indexing  [completions](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters-completion.html) with a large amount of categories in [context](https://www.elastic.co/guide/en/elasticsearch/reference/current/suggester-context.html)

**Comment by missinglink** [comment]
this issue is resolved as the plugin has been deprecated in favour of https://github.com/pelias/schema/blob/master/settings.js#L50-L59
