### ISSUE TITLE
Improve instructions regarding "add analyzer to settings mapping"

### ISSUE THREAD

**Issue by hahla** [pelias/elasticsearch-plugin#7]
I'm a new user and could not quite discern the instruction below, which seems critical to usage. Trying to install Pelias w/ES from the latest deb package on Ubuntu 14.04.

Here is my setup plan:
1. Install ES via deb 1.6.0
2a. Install elasticsearch-plugin into ES
2b. "Once the plugin is installed, you should restart ES and add the analyzer to your settings mapping, as shown in the ES site."
3. installed the index with node schema/scripts/create_index.js
4. linked the groovy scripts to my ES config/scripts directory
5. load data manually
6. run the api server

So in general I'm able to do everything above except 2b.

Current personal theories on how to do this and what I've tried to  "add the analyzer to your settings mapping" (no luck on any of the following 3):
- edit schema/settings.js. doesn't make much sense since if I was intended to edit it, why would it not be already in the proper configuration within the git repo in the first place? Also how does it get installed into ES
- manually copy the settings.js into the plugin jar file and repackage: elasticsearch-PeliasPlugin-1.3.4.jar
- in /etc/elasticsearch.elasticsearch.yml find a way to link it

**Comment by missinglink** [comment]
hi @hahla its a case of bad timing and unclear docs, sorry about that.

this plugin was actually deprecated and removed from the schema 10 days ago in this commit: https://github.com/pelias/schema/pull/67

so the good news is that you no longer need to install the plugin to use Pelias and you should be able to get it all running without modifying the schema yourself.

we have just completed a transition to a new architecture (I'm going to write a blog post on the specifics) so I'd recommend you pull the master branches again to get up to date with their state as of today.

I'm pretty sure the https://github.com/pelias/openstreetmap install docs are up-to-date

**Comment by hahla** [comment]
Awesome thanks @missinglink 

Definitely makes it easier now. And yes, I'm up and running. Good stuff.
